### ISSUE TITLE
Make ringrtc buildable on ARM64

### ISSUE THREAD

**Issue by DrWhax** [signalapp/ringrtc#11]
Hey signal team!

I'm trying to get ringrtc to build on ARM64, but I run into some issues! I don't think the scripts know what to do if it's discovering it's a non-standard Linux system that isn't x86_64. But I think I know how I would make a distinction in the scripts between linux_x64 and linux_aarch64.

I'm happy to provide patches and do the work if that's something you're interested in?

**Comment by jim-signal** [comment]
Hi @DrWhax! Thanks for the offer.

Generally we only want to support the environments and platforms our own clients need and that we can test on. But if there are changes that can be applied that give broader support, we'd love to see them. Please share a commit from your fork and we will take a look.
