### ISSUE TITLE
[Windows] Default communication device is picking a wrong output

### ISSUE THREAD

**Issue by maximbaz** [signalapp/ringrtc#23]
Hello,

Disclaimer: I'm reporting this bug on behalf of someone else, but I hope I've collected enough information to make a good description - and I am able to arrange to run more tests if needed.

#### Issue

The latest Signal on Windows does not respect the default communication device, and seems to always use the first available one.

#### Setup

It's a Windows laptop, with a TV plugged in with a cable. In Sound settings, there are two output devices: 

1. TV, called in logs '1 - SAMSUNG (AMD High Definition Audio Device)'
2. Internal speaker, called in logs 'Громкоговоритель и наушники (Realtek High Definition Audio)'

In the sound settings, it is possible to set either of these outputs as default media device and default communication device.

When internal speakers are set to be default everything, all applications respect this setting, and the sound is coming out of the speakers - all except Signal, who is always playing the sound out of the TV.

Restarting Signal doesn't help.

#### Repro steps

Here is a log performing the following test scenario:

https://debuglogs.org/4148a6154e8a945b562f0aa225ec8eb9a59c5c49b4aa00b00329b7854e877983

1. Close Signal.
1. Set Internal speakers to be the "default everything" device.
1. Launch Signal and start an audio call.
1. Audio is coming out of the TV ===> not the internal speakers.
1. In the call settings, look at the currently used output device ===> Signal uses "Default".
1. In the call settings, change the output device to TV ===> sound is still going out of TV (correct).
1. In the call settings, change the output device to internal speaker ===> sound is now going out of the internal speaker (correct).
1. In the call settings, change the output device back to "Default" ===> sound is going out of TV again (not internal speakers).

A subset of the logs of the final step:

```
MediaDevice: setPreferredSpeaker {"name":"Default","uniqueId":"Default","index":0,"i18nKey":"default_communication_device"}
"selectedSpeaker":{"name":"Default","uniqueId":"Default","index":0,"i18nKey":"default_communication_device"}
MediaDevice: selecting speaker {"name":"Default","uniqueId":"Default","index":0,"i18nKey":"default_communication_device"}
src\webrtc\peer_connection_factory.rs:379 PeerConnectionFactory::set_audio_playout_device(0)
src\webrtc\peer_connection_factory.rs:386 Picking default communication device (index 0)
```

Led me to https://github.com/signalapp/ringrtc/commit/364fbfccaa5afc0e3d196519fc07433ef057a840, which I'm trying to analyze next.

In order for this block to print "index 0":

https://github.com/signalapp/ringrtc/blob/a9845bd83cc5064f61430534309e7d98c02d4e87/src/rust/src/webrtc/peer_connection_factory.rs#L385-L389

This block must have `index` equal to `1`:

https://github.com/signalapp/ringrtc/blob/a9845bd83cc5064f61430534309e7d98c02d4e87/src/rust/src/webrtc/peer_connection_factory.rs#L368-L371

And since `all_devices` contains a synthetic device in index 0, `default_device` must be a reference to TV, since this is where the sound is coming from, right?

That means when passed `DEFAULT_COMMUNICATION_DEVICE_INDEX = 0xFFFF` here:

https://github.com/signalapp/ringrtc/blob/a9845bd83cc5064f61430534309e7d98c02d4e87/src/rust/src/webrtc/peer_connection_factory.rs#L311

Returns incorrectly TV as the default device, and not the internal speaker.

If I understand this correctly, eventually the code goes here:

https://github.com/signalapp/ringrtc/blob/a9845bd83cc5064f61430534309e7d98c02d4e87/src/rffi/src/peer_connection_factory.cc#L120

And then here:

https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/modules/audio_device/win/audio_device_core_win.cc#1500

Meaning that this might be a bug in WebRTC itself, and it e.g. just picks the first available output device, not the one marked as default?

What do you think, does the above tracing look correct?

I'm reasonably sure there is no mistake in configuring default device in Windows, I personally checked several places and everywhere internal speaker is set as default device (in Windows 10 settings, in tray > Sound internal speaker has green "default" icon next to it, no icon in front of TV), and all other apps (including call apps like Wire and Viber) do correctly use the internal speaker when it's set as default device, only Signal has this issue. (But I would be happy if you know a setting in Windows which I just need to adjust to fix this issue 😄 )

Especially since this is not my computer, I'm not sure what would be the best steps to move forward.

What would you suggest, would you be able to take this over, would you like me to gather some additional data / run more tests?

Thanks!

**Comment by jim-signal** [comment]
Wow, thanks for the detailed analysis @maximbaz!

There are several other reports of Windows audio issues too in Signal-Desktop, and your tracing might help. It doesn't seem to be any sort of configuration issue with the Windows audio devices in most cases... We'll be taking more of a look at this.

In WebRTC, there are some issues around the ADM (AudioDeviceModule) that we should take a look at. At this point I am not sure where the issue is though.

**Comment by jim-signal** [comment]
Hi, this issue should hopefully (and finally) be fixed in recent public Signal Desktop releases. RingRTC switched to use the newer ADM in WebRTC. This seems to have fixed a bunch of audio device issues experienced on Windows (device detection, selection, communications, echo, no audio played or recorded, ducking, etc.).

**Comment by maximbaz** [comment]
That's great news, thanks! 

I wouldn't be able to verify the fix (it was not my environment, I reported the bug on behalf of someone else who is out of reach for now), so I'll close the issue as fixed - you can always reopen, or create another one if necessary 🙂
