### ISSUE TITLE
Voice Call Encryption

### ISSUE THREAD

**Issue by hilmanfitriana19** [signalapp/ringrtc#30]
hello again, I'm trying to understand the workflow of voice calls encryption on the signal app. After trying to find out on the signal-android project, I was directed to this repository (ringrtc).
I then looked for the encrypt module which was most likely used to encrypt the voice call that occurred. I searched the file using the keyword `encrypt(` which should refer to the existing encryption function using vscode.
Here are the results of the existing search.

    - src/rffi/src/peer_connection_observer.cc line 166
    - src/rust/src/core/crypto.rs line 188
    - src/rust/src/core/group_call.rs line 2140

In the three modules, I added a simple log but after it was built and run on Android, the entered log was never called when a voice call was made.

Previously, this method was successfully used to find out and find the encryption function for the part of sending text messages.

What I want to ask is, is it true that the encrypt voice call module is in the `crypto.rs` file? If not, where is the location of the encrypt module for this voice call and what module in the ringrtc project is the bridge in calling the encrypt module?

**Comment by MuhammadAzamat** [comment]
Hi @hilmanfitriana19 
Did You solve Your issue? If Yes Can You complain it? Thanks!

**Comment by jrose-signal** [comment]
[Closing due to age, but note that in general this sort of question is better for the unofficial forums at https://community.signalusers.org/]

**Comment by MuhammadAzamat** [comment]
@jrose-signal Can You navigate with this?

**Comment by coder5492** [comment]
@hilmanfitriana19 Were you able to figure this out?
