### ISSUE TITLE
Question about your blog since I cannot find your personal contact information...

### ISSUE THREAD

**Issue by harlanc** [signalapp/ringrtc#36]
Hi @peter-signal  

Can I translate your [blog](https://signal.org/blog/how-to-build-encrypted-group-calls/) post into Chinese and then post it in my Chinese blog site?

I think it can help the guys who is in the video/audio area or newcomers..

Best wishes,
Harlanc

**Comment by peter-signal** [comment]
It's my decision.  But I'll forward your request to those who do make those
decisions.

**Comment by harlanc** [comment]
Thanks, so I can translate? or waiting response of someone who can do make the decisions?

**Comment by peter-signal** [comment]
I haven't gotten a response yet.  I'll keep asking.

**Comment by peter-signal** [comment]
OK, I got a response.  They said go ahead, but please provide a link back
to the original blog post.

**Comment by harlanc** [comment]
Okay, I will add the link in the post, thank you.
