### ISSUE TITLE
A note about the recent blog post on expanding group calls

### ISSUE THREAD

**Issue by ndgunebo** [signalapp/ringrtc#37]
Hi @peter-signal,

Great blog post at https://signal.org/blog/how-to-build-encrypted-group-calls! One comment: I noticed some of the GitHub links to lines of code are using the master branches of the repos. This can get out of sync overtime (if more lines are added or removed the line numbers won't match anymore), so I believe it would be best to use a commit hash or a tag.

**Comment by jrose-signal** [comment]
Thanks for catching this! Fixed all links to refer to current tags.
