### ISSUE TITLE
No call waiting support

### ISSUE THREAD

**Issue by Xashyar** [signalapp/ringrtc#4]
**Issue description:**
While on a Signal call every other call (Signal or otherwise) would be simply missed/dropped.

**Comment by cbrune-signal** [comment]
Hi @Xashyar, thanks for your comments.  We appreciate your interest in Signal.

We try to keep this github issue tracker focused on software bugs relating to RingRTC, which is an underlying library used for calling.  Call waiting is a feature in the purview of the client applications.

It is true that how incoming calls are handled while already in a call varies between iOS and Android.

Depending on which client you are using, one of these issue trackers is a better place to raise specific problems with existing features:

https://github.com/signalapp/Signal-Android
https://github.com/signalapp/Signal-iOS

For suggestions regarding overall improvements for a "call waiting" feature, the community forums is the place to go: https://community.signalusers.org/c/feature-requests.  There you can make client specific suggestions for improvement.  We definitely read the forums and factor the ideas into our planning process.

Again, thanks for being a Signal user.

**Comment by Xashyar** [comment]
@cbrune-signal 
Thanks for your detailed response.

If I'm understood correctly, this issue doesn't belong to ringrtc and is a client-related issue?

However I'm unclear whether this counts as a "**feature request**" (improvement) or an existing feature's "**functionality problem**".

For example, this same ambiguity applies to https://github.com/signalapp/Signal-Android/issues/9222 

I believe in general, such confusions would cause either delayed responses from the team or large piles of redundant issues generated from the users. Where both scenarios lead to undesired outcomes for both ends, so I'd love to hear any further comments.
