### ISSUE TITLE
Provide prebuilds for Windows + Linux arm64

### ISSUE THREAD

**Issue by dennisameling** [signalapp/ringrtc#40]
Hi Signal team,

Would it be possible to add prebuilds for Windows + Linux arm64 to [`signal-ringrtc-node`](https://github.com/signalapp/signal-ringrtc-node)? I've been building them in my [`signal-native-deps`](https://github.com/dennisameling/signal-native-deps/blob/34f9117a9f592665196b84afb37779023504391f/.github/workflows/build.yaml#L162-L282) repo for some months, but the dependencies are massive so I can't cache them properly. Therefore it takes about 1.5 hrs to build it for multiple architectures.

`libsignal-client` is already providing [Windows](https://github.com/signalapp/libsignal-client/pull/440) and [Linux arm64](https://github.com/signalapp/libsignal-client/pull/450) prebuilds even though Signal itself doesn't officially support those. I think that's a good middle way for the time being.

Thanks in advance!

**Comment by jim-signal** [comment]
@dennisameling Sure, we'll add them to the next build! Please take a look at them and close if they are okay.

**Comment by dennisameling** [comment]
Thanks, appreciate it! 😊

**Comment by balupton** [comment]
Now that all the other arm64 issues are closed, this is the last one right before we see signal desktop going on windows and linux arm64?
