### ISSUE TITLE
Build ringrtc aar file

### ISSUE THREAD

**Issue by MuhammadAzamat** [signalapp/ringrtc#41]
Hi there
I have successful build last "make android" command
But there is no *.aar file generated, 
Please help with this issue! Thanks!!!

**Comment by MuhammadAzamat** [comment]
Hi @jim-signal 
Can You explain all stack of ringrtc (c/c++, rust, java, bash, ...)
What should I go through to fully understand the project and customize it!
Thanks in advance!

**Comment by jim-signal** [comment]
Hi @MuhammadAzamat, if you have already run "make android" successfully, you could try this:

`./bin/build-aar --install-local`

It should put the aar file in your ~/.m2/org/signal directory.

RingRTC is a shared media stack meant for Signal's clients and has an internal API, so there is no public documentation for it other than the source code. In a nutshell, it wraps WebRTC with a layer created in Rust and then there is an FFI layer to each platform (iOS/Swift, Android/Java, Desktop/Typescript). A good place to start is definitely WebRTC for general media stack operation. The Rust part holds the logic for audio/video calling and you can look at the [Call Manager](https://github.com/signalapp/ringrtc/blob/main/src/rust/src/core/call_manager.rs) for the 'api'. WebRTC is written in C++, so we had use a [rffi layer](https://github.com/signalapp/ringrtc/tree/main/src/rffi) to convert between C and C++.

**Comment by MuhammadAzamat** [comment]
Thanks @jim-signal 
A lot for this information!
I'm going to research encryption process.
So, can You navigate where to start work with this, find out how happening encryption, What algorithm (I suggest AES), How to use other algorithms, how to trace packets, please.
Thanks in advance!!!
