### ISSUE TITLE
 Have problem when try to switch to another tags or branches

### ISSUE THREAD

**Issue by MuhammadAzamat** [signalapp/ringrtc#42]
Have problem when try to switch to another tags or branches
```
$ make android
$ Preparing Android workspace
$ Downloading WebRTC dependencies to /home/muhammad/projects/android_webrtc/ringrtc/src/webrtc from version 4896
$ /home/muhammad/projects/android_webrtc/ringrtc/bin/gsync-webrtc: 33: gclient: not found
$ make: *** [Makefile:51: out/android.env] Error 127

```

How to fix it?

**Comment by MuhammadAzamat** [comment]
Thanks @jim-signal 
Yes I fixed it, but now it says, That ".gclient seems broken, the URL is different"
If I can compile ringrtc-2.3.1 with the webrtc to use in version signal-android-4.61, because in ringrtc-2.3.20 changed webrtc version, and main classes also changed.

**Comment by MuhammadAzamat** [comment]
```
Preparing Android workspace
Downloading WebRTC dependencies to /home/muhammad/projects/android_webrtc/ringrtc/src/webrtc from version 4103
Updating depot_tools...
Error: 
Your .gclient file seems to be broken. The requested URL is different from what
is actually checked out in /home/muhammad/projects/android_webrtc/ringrtc/src/webrtc/src.

The .gclient file contains:
URL: git@github.com:signalapp/webrtc.git (git)
Cache mirror: not used

The local checkout in /home/muhammad/projects/android_webrtc/ringrtc/src/webrtc/src reports:
https://github.com/signalapp/webrtc.git (git)

You should ensure that the URL listed in .gclient is correct and either change
it or fix the checkout.

make: *** [Makefile:35: out/android.env] Error 1
```

**Comment by jim-signal** [comment]
It seems that version 2.3.1 is referencing `git@github.com:signalapp/webrtc.git` but in a later version that was switched to `https://github.com/signalapp/webrtc.git`. For such a large jump forward in versions, I highly recommend you remove the webrtc directory and then re-run prepare-workspace:

```
rm -rf src/webrtc
./bin/prepare-workspace android
```

Unfortunately it will take a while to download, but all the updated files would be downloaded anyway in this case.

**Comment by MuhammadAzamat** [comment]
Hi @jim-signal 
I'm doing what You adviced,  the downloading started successfully, but it hang up after while, it passed 24 hours and more.
What can You advice?

**Comment by MuhammadAzamat** [comment]
```
$ ./bin/prepare-workspace android
Downloading WebRTC dependencies to /home/muhammad/projects/android_webrtc/ringrtc/src/webrtc from version 4103
Updating depot_tools...
Enter passphrase for key '/home/muhammad/.ssh/id_rsa': 
Enter passphrase for key '/home/muhammad/.ssh/id_rsa': 
Syncing projects: 100% (261/261), done.      
```
and I'm waiting for end sync, but still such problem

**Comment by jim-signal** [comment]
Hello @MuhammadAzamat, it looks like you are trying to build an old version of RingRTC. It is possible that the newest version of depot_tools doesn't work with the old webrtc version. We can't support that combination, only the latest version of RingRTC. Is there a reason you need build v2.3.1?

**Comment by MuhammadAzamat** [comment]
Hello @jim-signal 
As I mentioned, I'm trying to run signal server and android app. So I worked with this since 2019.
Now I can not start with last stable server version and compatible version of android app.
I succeded to run signal-server-3.21 and signal-android-4.61, that's why I need recompile ringrtc-2.3.1 which is used in signal-android-4.6.
My tasks are:
- crash test webrtc calls for bugs or encryption;
- rebuild **ringrtc** with changed **encrypting algorithm** (try to replace AES for my government encrypting algorithm);
- run as latest versions of apps as possible;

I'm looking forward to **Your HELP**.

**Comment by jim-signal** [comment]
You could look here:  https://webrtc.googlesource.com/src/+/main/docs/native-code/development/index.md
- Look at the section "Working with Release Branches" and you could try to update depot_tools and src/webrtc outside of the RingRTC build scripts...

**Comment by MuhammadAzamat** [comment]
Thank You @jim-signal 
I will try it now.
But can You help with other things, please?
