### ISSUE TITLE
JNI: calling method failed.  Method: getTurnServerInfo

### ISSUE THREAD

**Issue by jithinpattattu** [signalapp/ringrtc#8]
After taking AAR file and linked to the project. while running i got the following exception.

JNI: calling method failed.  Method: getTurnServerInfo, Sig: ()Lorg/whispersystems/signalservice/api/messages/calls/TurnServerInfo; caused by java exception:
java.lang.NoSuchMethodError: no non-static method "Lorg/whispersystems/signalservice/api/SignalServiceAccountManager;.getTurnServerInfo()Lorg/whispersystems/signalservice/api/messages/calls/TurnServerInfo;"

**Comment by jim-signal** [comment]
Hi @jithinpattattu, do you still see this issue? I would suspect that the Signal-Android version was not compatible with the RingRTC one. Typically, new releases of RingRTC will lead the Signal-Android client releases (we release, they bring it in shortly afterward to beta, then later a release).

Either way, more information about the versions of RingRTC/Signal-Android you are using, your build environment, and build commands you tried would help clarify the issue.

**Comment by jim-signal** [comment]
Closing. If this is still a problem, please use the latest version of RingRTC and open a new issue.
